name: Compile xcbuild
on: [push]
jobs:
  linux:
    strategy:
      matrix:
        arch:
          - runner: ubuntu-22.04
            name: x86_64
          - runner: ubuntu-22.04-arm
            name: aarch64

    name: linux-${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Run compile script
        run: ./compile.sh

      - name: Zip idevicerestore
        run: zip -r build-${{ matrix.arch.name }}.zip build

      - name: Update latest release
        uses: pyTooling/Actions/releaser/composite@main
        with:
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build-${{ matrix.arch.name }}.zip
